//
// This file was automatically generated by openrpc-gen.
//
// Do not edit it manually and instead edit either the source OpenRPC document,
// the configuration file, or open an issue or pull request on the openrpc-gen
// GitHub repository.
//
//     https://github.com/nils-mathieu/openrpc-gen
//

use serde::{Deserialize, Serialize};

// #/components/schemas/ADDRESS
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type Address = Felt;

// #/components/schemas/BLOCK_BODY_WITH_TXS/transactions/_anon/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TxnWithHash {
    // #/components/schemas/BLOCK_BODY_WITH_TXS/transactions/_anon/_anon/field0
    #[serde(flatten)]
    pub transaction: Txn,
    // #/components/schemas/BLOCK_BODY_WITH_TXS/transactions/_anon/_anon/field1/_anon/transaction_hash
    pub transaction_hash: TxnHash,
}

// #/components/schemas/BLOCK_HASH
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type BlockHash = Felt;

// #/components/schemas/BLOCK_HEADER
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockHeader {
    // #/components/schemas/BLOCK_HEADER/block_hash
    pub block_hash: BlockHash,
    // #/components/schemas/BLOCK_HEADER/block_number
    /// The block number (its height)
    pub block_number: BlockNumber,
    // #/components/schemas/BLOCK_HEADER/l1_gas_price
    pub l1_gas_price: ResourcePrice,
    // #/components/schemas/BLOCK_HEADER/new_root
    /// The new global state root
    pub new_root: Felt,
    // #/components/schemas/BLOCK_HEADER/parent_hash
    /// The hash of this block's parent
    pub parent_hash: BlockHash,
    // #/components/schemas/BLOCK_HEADER/sequencer_address
    /// The StarkNet identity of the sequencer submitting this block
    pub sequencer_address: Felt,
    // #/components/schemas/BLOCK_HEADER/starknet_version
    /// Semver of the current Starknet protocol
    pub starknet_version: String,
    // #/components/schemas/BLOCK_HEADER/timestamp
    /// The time in which the block was created, encoded in Unix time
    pub timestamp: u64,
}

// #/components/schemas/BLOCK_NUMBER
/// The block's number (its height)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type BlockNumber = u64;

// #/components/schemas/BLOCK_STATUS
/// The status of the block
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BlockStatus {
    // #/components/schemas/BLOCK_STATUS/ACCEPTED_ON_L1
    #[serde(rename = "ACCEPTED_ON_L1")]
    AcceptedOnL1,
    // #/components/schemas/BLOCK_STATUS/ACCEPTED_ON_L2
    #[serde(rename = "ACCEPTED_ON_L2")]
    AcceptedOnL2,
    // #/components/schemas/BLOCK_STATUS/PENDING
    #[serde(rename = "PENDING")]
    Pending,
    // #/components/schemas/BLOCK_STATUS/REJECTED
    #[serde(rename = "REJECTED")]
    Rejected,
}

// #/components/schemas/BLOCK_WITH_TXS
/// The block object
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockWithTxs {
    // #/components/schemas/BLOCK_BODY_WITH_TXS/transactions
    /// The transactions in this block
    pub transactions: Vec<TxnWithHash>,
    // #/components/schemas/BLOCK_WITH_TXS/field0/_anon/status
    pub status: BlockStatus,
    // #/components/schemas/BLOCK_WITH_TXS/field1
    #[serde(flatten)]
    pub block_header: BlockHeader,
}

// #/components/schemas/BLOCK_WITH_TX_HASHES
/// The block object
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockWithTxHashes {
    // #/components/schemas/BLOCK_BODY_WITH_TX_HASHES/transactions
    /// The hashes of the transactions included in this block
    pub transactions: Vec<TxnHash>,
    // #/components/schemas/BLOCK_WITH_TX_HASHES/field0/_anon/status
    pub status: BlockStatus,
    // #/components/schemas/BLOCK_WITH_TX_HASHES/field1
    #[serde(flatten)]
    pub block_header: BlockHeader,
}

// #/components/schemas/COMMON_RECEIPT_PROPERTIES
/// Common properties for a transaction receipt
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommonReceiptProperties {
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/actual_fee
    /// The fee that was charged by the sequencer
    pub actual_fee: Felt,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/block_hash
    pub block_hash: BlockHash,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/block_number
    pub block_number: BlockNumber,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/events
    /// The events emitted as part of this transaction
    pub events: Vec<Event>,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/execution_resources
    /// The resources consumed by the transaction
    pub execution_resources: ExecutionResources,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/execution_status
    pub execution_status: TxnExecutionStatus,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/finality_status
    pub finality_status: TxnFinalityStatus,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/messages_sent
    pub messages_sent: Vec<MsgToL1>,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/revert_reason
    /// the revert reason for the failed execution
    #[serde(default)]
    pub revert_reason: Option<String>,
    // #/components/schemas/COMMON_RECEIPT_PROPERTIES/transaction_hash
    /// The hash identifying the transaction
    pub transaction_hash: TxnHash,
}

// #/components/schemas/CONTRACT_ABI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type ContractAbi = Vec<ContractAbiEntry>;

// #/components/schemas/CONTRACT_ABI_ENTRY
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContractAbiEntry {
    // #/components/schemas/CONTRACT_ABI_ENTRY/variant0
    Function(FunctionAbiEntry),
    // #/components/schemas/CONTRACT_ABI_ENTRY/variant1
    Event(EventAbiEntry),
    // #/components/schemas/CONTRACT_ABI_ENTRY/variant2
    Struct(StructAbiEntry),
}

// #/components/schemas/CONTRACT_CLASS
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContractClass {
    // #/components/schemas/CONTRACT_CLASS/abi
    /// The class ABI, as supplied by the user declaring the class
    #[serde(default)]
    pub abi: Option<String>,
    // #/components/schemas/CONTRACT_CLASS/contract_class_version
    /// The version of the contract class object. Currently, the Starknet OS supports version 0.1.0
    pub contract_class_version: String,
    // #/components/schemas/CONTRACT_CLASS/entry_points_by_type
    pub entry_points_by_type: EntryPointsByType,
    // #/components/schemas/CONTRACT_CLASS/sierra_program
    /// The list of Sierra instructions of which the program consists
    pub sierra_program: Vec<Felt>,
}

// #/components/schemas/CONTRACT_CLASS/entry_points_by_type/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntryPointsByType {
    // #/components/schemas/CONTRACT_CLASS/entry_points_by_type/_anon/CONSTRUCTOR
    #[serde(rename = "CONSTRUCTOR")]
    pub constructor: Vec<SierraEntryPoint>,
    // #/components/schemas/CONTRACT_CLASS/entry_points_by_type/_anon/EXTERNAL
    #[serde(rename = "EXTERNAL")]
    pub external: Vec<SierraEntryPoint>,
    // #/components/schemas/CONTRACT_CLASS/entry_points_by_type/_anon/L1_HANDLER
    #[serde(rename = "L1_HANDLER")]
    pub l1_handler: Vec<SierraEntryPoint>,
}

// #/components/schemas/CONTRACT_STORAGE_DIFF_ITEM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContractStorageDiffItem {
    // #/components/schemas/CONTRACT_STORAGE_DIFF_ITEM/address
    /// The contract address for which the storage changed
    pub address: Felt,
    // #/components/schemas/CONTRACT_STORAGE_DIFF_ITEM/storage_entries
    /// The changes in the storage of the contract
    pub storage_entries: Vec<KeyValuePair>,
}

// #/components/schemas/CONTRACT_STORAGE_DIFF_ITEM/storage_entries/_anon/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyValuePair {
    // #/components/schemas/CONTRACT_STORAGE_DIFF_ITEM/storage_entries/_anon/_anon/key
    /// The key of the changed value
    #[serde(default)]
    pub key: Option<Felt>,
    // #/components/schemas/CONTRACT_STORAGE_DIFF_ITEM/storage_entries/_anon/_anon/value
    /// The new value applied to the given address
    #[serde(default)]
    pub value: Option<Felt>,
}

// #/components/schemas/DECLARE_TXN
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "version")]
pub enum DeclareTxn {
    // #/components/schemas/DECLARE_TXN/variant0
    #[serde(rename = "0x0")]
    V0(DeclareTxnV0),
    // #/components/schemas/DECLARE_TXN/variant1
    #[serde(rename = "0x1")]
    V1(DeclareTxnV1),
    // #/components/schemas/DECLARE_TXN/variant2
    #[serde(rename = "0x2")]
    V2(DeclareTxnV2),
}

// #/components/schemas/DECLARE_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeclareTxnReceipt {
    // #/components/schemas/DECLARE_TXN_RECEIPT/field1
    #[serde(flatten)]
    pub common_receipt_properties: CommonReceiptProperties,
}

// #/components/schemas/DECLARE_TXN_V0
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeclareTxnV0 {
    // #/components/schemas/DECLARE_TXN_V0/_anon/class_hash
    /// The hash of the declared class
    pub class_hash: Felt,
    // #/components/schemas/DECLARE_TXN_V0/_anon/max_fee
    /// The maximal fee that can be charged for including the transaction
    pub max_fee: Felt,
    // #/components/schemas/DECLARE_TXN_V0/_anon/sender_address
    /// The address of the account contract sending the declaration transaction
    pub sender_address: Address,
    // #/components/schemas/DECLARE_TXN_V0/_anon/signature
    pub signature: Signature,
}

// #/components/schemas/DECLARE_TXN_V1
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeclareTxnV1 {
    // #/components/schemas/DECLARE_TXN_V1/_anon/class_hash
    /// The hash of the declared class
    pub class_hash: Felt,
    // #/components/schemas/DECLARE_TXN_V1/_anon/max_fee
    /// The maximal fee that can be charged for including the transaction
    pub max_fee: Felt,
    // #/components/schemas/DECLARE_TXN_V1/_anon/nonce
    pub nonce: Felt,
    // #/components/schemas/DECLARE_TXN_V1/_anon/sender_address
    /// The address of the account contract sending the declaration transaction
    pub sender_address: Address,
    // #/components/schemas/DECLARE_TXN_V1/_anon/signature
    pub signature: Signature,
}

// #/components/schemas/DECLARE_TXN_V2
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeclareTxnV2 {
    // #/components/schemas/DECLARE_TXN_V2/_anon/class_hash
    /// The hash of the declared class
    pub class_hash: Felt,
    // #/components/schemas/DECLARE_TXN_V2/_anon/compiled_class_hash
    /// The hash of the Cairo assembly resulting from the Sierra compilation
    pub compiled_class_hash: Felt,
    // #/components/schemas/DECLARE_TXN_V2/_anon/max_fee
    /// The maximal fee that can be charged for including the transaction
    pub max_fee: Felt,
    // #/components/schemas/DECLARE_TXN_V2/_anon/nonce
    pub nonce: Felt,
    // #/components/schemas/DECLARE_TXN_V2/_anon/sender_address
    /// The address of the account contract sending the declaration transaction
    pub sender_address: Address,
    // #/components/schemas/DECLARE_TXN_V2/_anon/signature
    pub signature: Signature,
}

// #/components/schemas/DEPLOYED_CONTRACT_ITEM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployedContractItem {
    // #/components/schemas/DEPLOYED_CONTRACT_ITEM/address
    /// The address of the contract
    pub address: Felt,
    // #/components/schemas/DEPLOYED_CONTRACT_ITEM/class_hash
    /// The hash of the contract code
    pub class_hash: Felt,
}

// #/components/schemas/DEPLOY_ACCOUNT_TXN
/// deploys a new account contract
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeployAccountTxn {
    // #/components/schemas/DEPLOY_ACCOUNT_TXN/variant0
    DeployAccountV1(DeployAccountTxnV1),
}

// #/components/schemas/DEPLOY_ACCOUNT_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployAccountTxnReceipt {
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_RECEIPT/field0
    #[serde(flatten)]
    pub common_receipt_properties: CommonReceiptProperties,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_RECEIPT/field1/_anon/contract_address
    /// The address of the deployed contract
    pub contract_address: Felt,
}

// #/components/schemas/DEPLOY_ACCOUNT_TXN_V1
/// Deploys an account contract, charges fee from the pre-funded account addresses
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployAccountTxnV1 {
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/class_hash
    /// The hash of the deployed contract's class
    pub class_hash: Felt,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/constructor_calldata
    /// The parameters passed to the constructor
    pub constructor_calldata: Vec<Felt>,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/contract_address_salt
    /// The salt for the address of the deployed contract
    pub contract_address_salt: Felt,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/max_fee
    /// The maximal fee that can be charged for including the transaction
    pub max_fee: Felt,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/nonce
    pub nonce: Felt,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/signature
    pub signature: Signature,
    // #/components/schemas/DEPLOY_ACCOUNT_TXN_V1/version
    /// Version of the transaction scheme
    pub version: NumAsHex,
}

// #/components/schemas/DEPLOY_TXN
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployTxn {
    // #/components/schemas/DEPLOY_TXN/_anon/class_hash
    /// The hash of the deployed contract's class
    pub class_hash: Felt,
    // #/components/schemas/DEPLOY_TXN/_anon/constructor_calldata
    /// The parameters passed to the constructor
    pub constructor_calldata: Vec<Felt>,
    // #/components/schemas/DEPLOY_TXN/_anon/contract_address_salt
    /// The salt for the address of the deployed contract
    pub contract_address_salt: Felt,
    // #/components/schemas/DEPLOY_TXN/_anon/version
    /// Version of the transaction scheme
    pub version: NumAsHex,
}

// #/components/schemas/DEPLOY_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployTxnReceipt {
    // #/components/schemas/DEPLOY_TXN_RECEIPT/field0
    #[serde(flatten)]
    pub common_receipt_properties: CommonReceiptProperties,
    // #/components/schemas/DEPLOY_TXN_RECEIPT/field1/_anon/contract_address
    /// The address of the deployed contract
    pub contract_address: Felt,
}

// #/components/schemas/DEPRECATED_CAIRO_ENTRY_POINT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeprecatedCairoEntryPoint {
    // #/components/schemas/DEPRECATED_CAIRO_ENTRY_POINT/offset
    /// The offset of the entry point in the program
    pub offset: NumAsHex,
    // #/components/schemas/DEPRECATED_CAIRO_ENTRY_POINT/selector
    /// A unique identifier of the entry point (function) in the program
    pub selector: Felt,
}

// #/components/schemas/DEPRECATED_CONTRACT_CLASS
/// The definition of a StarkNet contract class
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeprecatedContractClass {
    // #/components/schemas/DEPRECATED_CONTRACT_CLASS/abi
    #[serde(default)]
    pub abi: Option<ContractAbi>,
    // #/components/schemas/DEPRECATED_CONTRACT_CLASS/entry_points_by_type
    pub entry_points_by_type: DeprecatedEntryPointsByType,
    // #/components/schemas/DEPRECATED_CONTRACT_CLASS/program
    /// A base64 representation of the compressed program code
    pub program: String,
}

// #/components/schemas/DEPRECATED_CONTRACT_CLASS/entry_points_by_type/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeprecatedEntryPointsByType {
    // #/components/schemas/DEPRECATED_CONTRACT_CLASS/entry_points_by_type/_anon/CONSTRUCTOR
    #[serde(default)]
    #[serde(rename = "CONSTRUCTOR")]
    pub constructor: Option<Vec<DeprecatedCairoEntryPoint>>,
    // #/components/schemas/DEPRECATED_CONTRACT_CLASS/entry_points_by_type/_anon/EXTERNAL
    #[serde(default)]
    #[serde(rename = "EXTERNAL")]
    pub external: Option<Vec<DeprecatedCairoEntryPoint>>,
    // #/components/schemas/DEPRECATED_CONTRACT_CLASS/entry_points_by_type/_anon/L1_HANDLER
    #[serde(default)]
    #[serde(rename = "L1_HANDLER")]
    pub l1_handler: Option<Vec<DeprecatedCairoEntryPoint>>,
}

// #/components/schemas/EVENT
/// A StarkNet event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    // #/components/schemas/EVENT/field0/_anon/from_address
    pub from_address: Address,
    // #/components/schemas/EVENT_CONTENT/data
    pub data: Vec<Felt>,
    // #/components/schemas/EVENT_CONTENT/keys
    pub keys: Vec<Felt>,
}

// #/components/schemas/EVENT_ABI_ENTRY
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventAbiEntry {
    // #/components/schemas/EVENT_ABI_ENTRY/data
    pub data: Vec<TypedParameter>,
    // #/components/schemas/EVENT_ABI_ENTRY/keys
    pub keys: Vec<TypedParameter>,
    // #/components/schemas/EVENT_ABI_ENTRY/name
    /// The event name
    pub name: String,
    // #/components/schemas/EVENT_ABI_ENTRY/type
    #[serde(rename = "type")]
    pub ty: EventAbiType,
}

// #/components/schemas/EVENT_ABI_TYPE
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type EventAbiType = String;

// #/components/schemas/EXECUTION_RESOURCES
/// The resources consumed by the transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionResources {
    // #/components/schemas/EXECUTION_RESOURCES/bitwise_builtin_applications
    /// the number of BITWISE builtin instances
    pub bitwise_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/ec_op_builtin_applications
    /// the number of EC_OP builtin instances
    pub ec_op_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/ecdsa_builtin_applications
    /// the number of ECDSA builtin instances
    pub ecdsa_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/keccak_builtin_applications
    /// The number of KECCAK builtin instances
    pub keccak_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/memory_holes
    /// The number of unused memory cells (each cell is roughly equivalent to a step)
    #[serde(default)]
    pub memory_holes: Option<u64>,
    // #/components/schemas/EXECUTION_RESOURCES/pedersen_builtin_applications
    /// The number of Pedersen builtin instances
    pub pedersen_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/poseidon_builtin_applications
    /// The number of Poseidon builtin instances
    pub poseidon_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/range_check_builtin_applications
    /// The number of RANGE_CHECK builtin instances
    pub range_check_builtin_applications: u64,
    // #/components/schemas/EXECUTION_RESOURCES/steps
    /// The number of Cairo steps used
    pub steps: u64,
}

// #/components/schemas/FELT
/// A field element. represented by at most 63 hex digits
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type Felt = String;

// #/components/schemas/FUNCTION_ABI_ENTRY
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionAbiEntry {
    // #/components/schemas/FUNCTION_ABI_ENTRY/inputs
    pub inputs: Vec<TypedParameter>,
    // #/components/schemas/FUNCTION_ABI_ENTRY/name
    /// The function name
    pub name: String,
    // #/components/schemas/FUNCTION_ABI_ENTRY/outputs
    pub outputs: Vec<TypedParameter>,
    // #/components/schemas/FUNCTION_ABI_ENTRY/stateMutability
    #[serde(default)]
    #[serde(rename = "stateMutability")]
    pub statemutability: Option<FunctionStateMutability>,
    // #/components/schemas/FUNCTION_ABI_ENTRY/type
    #[serde(rename = "type")]
    pub ty: FunctionAbiType,
}

// #/components/schemas/FUNCTION_ABI_TYPE
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FunctionAbiType {
    // #/components/schemas/FUNCTION_ABI_TYPE/constructor
    #[serde(rename = "constructor")]
    Constructor,
    // #/components/schemas/FUNCTION_ABI_TYPE/function
    #[serde(rename = "function")]
    Function,
    // #/components/schemas/FUNCTION_ABI_TYPE/l1_handler
    #[serde(rename = "l1_handler")]
    L1Handler,
}

// #/components/schemas/FUNCTION_STATE_MUTABILITY
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type FunctionStateMutability = String;

// #/components/schemas/INVOKE_TXN
/// Initiate a transaction from an account
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InvokeTxn {
    // #/components/schemas/INVOKE_TXN/variant0
    V0(InvokeTxnV0),
    // #/components/schemas/INVOKE_TXN/variant1
    V1(Anonymous),
}

// #/components/schemas/INVOKE_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvokeTxnReceipt {
    // #/components/schemas/INVOKE_TXN_RECEIPT/field1
    #[serde(flatten)]
    pub common_receipt_properties: CommonReceiptProperties,
}

// #/components/schemas/INVOKE_TXN_V0
/// invokes a specific function in the desired contract (not necessarily an account)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvokeTxnV0 {
    // #/components/schemas/INVOKE_TXN_V0/calldata
    /// The parameters passed to the function
    pub calldata: Vec<Felt>,
    // #/components/schemas/INVOKE_TXN_V0/contract_address
    pub contract_address: Address,
    // #/components/schemas/INVOKE_TXN_V0/entry_point_selector
    pub entry_point_selector: Felt,
    // #/components/schemas/INVOKE_TXN_V0/max_fee
    /// The maximal fee that can be charged for including the transaction
    pub max_fee: Felt,
    // #/components/schemas/INVOKE_TXN_V0/signature
    pub signature: Signature,
    // #/components/schemas/INVOKE_TXN_V0/version
    /// Version of the transaction scheme
    pub version: String, /* 0x0 */
}

// #/components/schemas/INVOKE_TXN_V1
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Anonymous {
    // #/components/schemas/INVOKE_TXN_V1/_anon/calldata
    /// The data expected by the account's `execute` function (in most usecases, this includes the called contract address and a function selector)
    pub calldata: Vec<Felt>,
    // #/components/schemas/INVOKE_TXN_V1/_anon/max_fee
    /// The maximal fee that can be charged for including the transaction
    pub max_fee: Felt,
    // #/components/schemas/INVOKE_TXN_V1/_anon/nonce
    pub nonce: Felt,
    // #/components/schemas/INVOKE_TXN_V1/_anon/sender_address
    pub sender_address: Address,
    // #/components/schemas/INVOKE_TXN_V1/_anon/signature
    pub signature: Signature,
    // #/components/schemas/INVOKE_TXN_V1/_anon/version
    /// Version of the transaction scheme
    pub version: NumAsHex,
}

// #/components/schemas/L1_HANDLER_TXN
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct L1HandlerTxn {
    // #/components/schemas/FUNCTION_CALL/calldata
    /// The parameters passed to the function
    pub calldata: Vec<Felt>,
    // #/components/schemas/FUNCTION_CALL/contract_address
    pub contract_address: Address,
    // #/components/schemas/FUNCTION_CALL/entry_point_selector
    pub entry_point_selector: Felt,
    // #/components/schemas/L1_HANDLER_TXN/field0/_anon/nonce
    /// The L1->L2 message nonce field of the SN Core L1 contract at the time the transaction was sent
    pub nonce: NumAsHex,
    // #/components/schemas/L1_HANDLER_TXN/field0/_anon/version
    /// Version of the transaction scheme
    pub version: NumAsHex,
}

// #/components/schemas/L1_HANDLER_TXN_RECEIPT
/// receipt for l1 handler transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct L1HandlerTxnReceipt {
    // #/components/schemas/L1_HANDLER_TXN_RECEIPT/field0/_anon/message_hash
    /// The message hash as it appears on the L1 core contract
    pub message_hash: NumAsHex,
    // #/components/schemas/L1_HANDLER_TXN_RECEIPT/field1
    #[serde(flatten)]
    pub common_receipt_properties: CommonReceiptProperties,
}

// #/components/schemas/MSG_TO_L1
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MsgToL1 {
    // #/components/schemas/MSG_TO_L1/from_address
    /// The address of the L2 contract sending the message
    pub from_address: Felt,
    // #/components/schemas/MSG_TO_L1/payload
    /// The payload of the message
    pub payload: Vec<Felt>,
    // #/components/schemas/MSG_TO_L1/to_address
    /// The target L1 address the message is sent to
    pub to_address: Felt,
}

// #/components/schemas/NUM_AS_HEX
/// An integer number in hex format (0x...)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type NumAsHex = String;

// #/components/schemas/PENDING_BLOCK_HEADER
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingBlockHeader {
    // #/components/schemas/PENDING_BLOCK_HEADER/l1_gas_price
    pub l1_gas_price: ResourcePrice,
    // #/components/schemas/PENDING_BLOCK_HEADER/parent_hash
    /// The hash of this block's parent
    pub parent_hash: BlockHash,
    // #/components/schemas/PENDING_BLOCK_HEADER/sequencer_address
    /// The StarkNet identity of the sequencer submitting this block
    pub sequencer_address: Felt,
    // #/components/schemas/PENDING_BLOCK_HEADER/starknet_version
    /// Semver of the current Starknet protocol
    pub starknet_version: String,
    // #/components/schemas/PENDING_BLOCK_HEADER/timestamp
    /// The time in which the block was created, encoded in Unix time
    pub timestamp: u64,
}

// #/components/schemas/PENDING_BLOCK_WITH_TXS
/// The dynamic block being constructed by the sequencer. Note that this object will be deprecated upon decentralization.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingBlockWithTxs {
    // #/components/schemas/BLOCK_BODY_WITH_TXS/transactions
    /// The transactions in this block
    pub transactions: Vec<TxnWithHash>,
    // #/components/schemas/PENDING_BLOCK_WITH_TXS/field1
    #[serde(flatten)]
    pub pending_block_header: PendingBlockHeader,
}

// #/components/schemas/PENDING_BLOCK_WITH_TX_HASHES
/// The dynamic block being constructed by the sequencer. Note that this object will be deprecated upon decentralization.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingBlockWithTxHashes {
    // #/components/schemas/BLOCK_BODY_WITH_TX_HASHES/transactions
    /// The hashes of the transactions included in this block
    pub transactions: Vec<TxnHash>,
    // #/components/schemas/PENDING_BLOCK_WITH_TX_HASHES/field1
    #[serde(flatten)]
    pub pending_block_header: PendingBlockHeader,
}

// #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES
/// Common properties for a pending transaction receipt
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingCommonReceiptProperties {
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/actual_fee
    /// The fee that was charged by the sequencer
    pub actual_fee: Felt,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/events
    /// The events emitted as part of this transaction
    pub events: Vec<Event>,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/execution_resources
    /// The resources consumed by the transaction
    pub execution_resources: ExecutionResources,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/execution_status
    pub execution_status: TxnExecutionStatus,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/finality_status
    /// The finality status of the transaction
    pub finality_status: String, /* ACCEPTED_ON_L2 */
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/messages_sent
    pub messages_sent: Vec<MsgToL1>,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/revert_reason
    /// the revert reason for the failed execution
    #[serde(default)]
    pub revert_reason: Option<String>,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/transaction_hash
    /// The hash identifying the transaction
    pub transaction_hash: TxnHash,
    // #/components/schemas/PENDING_COMMON_RECEIPT_PROPERTIES/type
    #[serde(rename = "type")]
    pub ty: TxnType,
}

// #/components/schemas/PENDING_DECLARE_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingDeclareTxnReceipt {
    // #/components/schemas/PENDING_DECLARE_TXN_RECEIPT/field1
    #[serde(flatten)]
    pub common_receipt_properties: PendingCommonReceiptProperties,
}

// #/components/schemas/PENDING_DEPLOY_ACCOUNT_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingDeployAccountTxnReceipt {
    // #/components/schemas/PENDING_DEPLOY_ACCOUNT_TXN_RECEIPT/field0
    #[serde(flatten)]
    pub common_receipt_properties: PendingCommonReceiptProperties,
    // #/components/schemas/PENDING_DEPLOY_ACCOUNT_TXN_RECEIPT/field1/_anon/contract_address
    /// The address of the deployed contract
    pub contract_address: Felt,
}

// #/components/schemas/PENDING_INVOKE_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingInvokeTxnReceipt {
    // #/components/schemas/PENDING_INVOKE_TXN_RECEIPT/field1
    #[serde(flatten)]
    pub common_receipt_properties: PendingCommonReceiptProperties,
}

// #/components/schemas/PENDING_L1_HANDLER_TXN_RECEIPT
/// receipt for l1 handler transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingL1HandlerTxnReceipt {
    // #/components/schemas/PENDING_L1_HANDLER_TXN_RECEIPT/field0/_anon/message_hash
    /// The message hash as it appears on the L1 core contract
    pub message_hash: NumAsHex,
    // #/components/schemas/PENDING_L1_HANDLER_TXN_RECEIPT/field1
    #[serde(flatten)]
    pub common_receipt_properties: PendingCommonReceiptProperties,
}

// #/components/schemas/PENDING_STATE_UPDATE
/// Pending state update
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingStateUpdate {
    // #/components/schemas/PENDING_STATE_UPDATE/old_root
    /// The previous global state root
    pub old_root: Felt,
    // #/components/schemas/PENDING_STATE_UPDATE/state_diff
    pub state_diff: StateDiff,
}

// #/components/schemas/PENDING_TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PendingTxnReceipt {
    // #/components/schemas/PENDING_TXN_RECEIPT/variant0
    #[serde(rename = "INVOKE")]
    Invoke(PendingInvokeTxnReceipt),
    // #/components/schemas/PENDING_TXN_RECEIPT/variant1
    #[serde(rename = "L1_HANDLER")]
    L1Handler(PendingL1HandlerTxnReceipt),
    // #/components/schemas/PENDING_TXN_RECEIPT/variant2
    #[serde(rename = "DECLARE")]
    Declare(PendingDeclareTxnReceipt),
    // #/components/schemas/PENDING_TXN_RECEIPT/variant3
    #[serde(rename = "DEPLOY_ACCOUNT")]
    DeployAccount(PendingDeployAccountTxnReceipt),
}

// #/components/schemas/RESOURCE_PRICE
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourcePrice {
    // #/components/schemas/RESOURCE_PRICE/price_in_strk
    /// the price of one unit of the given resource, denominated in strk
    #[serde(default)]
    pub price_in_strk: Option<NumAsHex>,
    // #/components/schemas/RESOURCE_PRICE/price_in_wei
    /// the price of one unit of the given resource, denominated in wei
    pub price_in_wei: NumAsHex,
}

// #/components/schemas/SIERRA_ENTRY_POINT
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SierraEntryPoint {
    // #/components/schemas/SIERRA_ENTRY_POINT/function_idx
    /// The index of the function in the program
    pub function_idx: u64,
    // #/components/schemas/SIERRA_ENTRY_POINT/selector
    /// A unique identifier of the entry point (function) in the program
    pub selector: Felt,
}

// #/components/schemas/SIGNATURE
/// A transaction signature
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type Signature = Vec<Felt>;

// #/components/schemas/STATE_DIFF
/// The change in state applied in this block, given as a mapping of addresses to the new values and/or new contracts
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateDiff {
    // #/components/schemas/STATE_DIFF/declared_classes
    pub declared_classes: Vec<NewClasses>,
    // #/components/schemas/STATE_DIFF/deployed_contracts
    pub deployed_contracts: Vec<DeployedContractItem>,
    // #/components/schemas/STATE_DIFF/deprecated_declared_classes
    pub deprecated_declared_classes: Vec<Felt>,
    // #/components/schemas/STATE_DIFF/nonces
    pub nonces: Vec<NonceUpdate>,
    // #/components/schemas/STATE_DIFF/replaced_classes
    pub replaced_classes: Vec<ReplacedClass>,
    // #/components/schemas/STATE_DIFF/storage_diffs
    pub storage_diffs: Vec<ContractStorageDiffItem>,
}

// #/components/schemas/STATE_DIFF/declared_classes/_anon/_anon
/// The declared class hash and compiled class hash
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewClasses {
    // #/components/schemas/STATE_DIFF/declared_classes/_anon/_anon/class_hash
    /// The hash of the declared class
    #[serde(default)]
    pub class_hash: Option<Felt>,
    // #/components/schemas/STATE_DIFF/declared_classes/_anon/_anon/compiled_class_hash
    /// The Cairo assembly hash corresponding to the declared class
    #[serde(default)]
    pub compiled_class_hash: Option<Felt>,
}

// #/components/schemas/STATE_DIFF/nonces/_anon/_anon
/// The updated nonce per contract address
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonceUpdate {
    // #/components/schemas/STATE_DIFF/nonces/_anon/_anon/contract_address
    /// The address of the contract
    #[serde(default)]
    pub contract_address: Option<Address>,
    // #/components/schemas/STATE_DIFF/nonces/_anon/_anon/nonce
    /// The nonce for the given address at the end of the block
    #[serde(default)]
    pub nonce: Option<Felt>,
}

// #/components/schemas/STATE_DIFF/replaced_classes/_anon/_anon
/// The list of contracts whose class was replaced
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplacedClass {
    // #/components/schemas/STATE_DIFF/replaced_classes/_anon/_anon/class_hash
    /// The new class hash
    #[serde(default)]
    pub class_hash: Option<Felt>,
    // #/components/schemas/STATE_DIFF/replaced_classes/_anon/_anon/contract_address
    /// The address of the contract whose class was replaced
    #[serde(default)]
    pub contract_address: Option<Address>,
}

// #/components/schemas/STATE_UPDATE
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateUpdate {
    // #/components/schemas/STATE_UPDATE/block_hash
    pub block_hash: BlockHash,
    // #/components/schemas/STATE_UPDATE/new_root
    /// The new global state root
    pub new_root: Felt,
    // #/components/schemas/STATE_UPDATE/old_root
    /// The previous global state root
    pub old_root: Felt,
    // #/components/schemas/STATE_UPDATE/state_diff
    pub state_diff: StateDiff,
}

// #/components/schemas/STRUCT_ABI_ENTRY
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StructAbiEntry {
    // #/components/schemas/STRUCT_ABI_ENTRY/members
    pub members: Vec<StructMember>,
    // #/components/schemas/STRUCT_ABI_ENTRY/name
    /// The struct name
    pub name: String,
    // #/components/schemas/STRUCT_ABI_ENTRY/size
    pub size: u64,
    // #/components/schemas/STRUCT_ABI_ENTRY/type
    #[serde(rename = "type")]
    pub ty: StructAbiType,
}

// #/components/schemas/STRUCT_ABI_TYPE
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type StructAbiType = String;

// #/components/schemas/STRUCT_MEMBER
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StructMember {
    // #/components/schemas/STRUCT_MEMBER/field0
    #[serde(flatten)]
    pub typed_parameter: TypedParameter,
    // #/components/schemas/STRUCT_MEMBER/field1/_anon/offset
    /// offset of this property within the struct
    #[serde(default)]
    pub offset: Option<u64>,
}

// #/components/schemas/SYNC_STATUS
/// An object describing the node synchronization status
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncStatus {
    // #/components/schemas/SYNC_STATUS/current_block_hash
    /// The hash of the current block being synchronized
    pub current_block_hash: BlockHash,
    // #/components/schemas/SYNC_STATUS/current_block_num
    /// The number (height) of the current block being synchronized
    pub current_block_num: BlockNumber,
    // #/components/schemas/SYNC_STATUS/highest_block_hash
    /// The hash of the estimated highest block to be synchronized
    pub highest_block_hash: BlockHash,
    // #/components/schemas/SYNC_STATUS/highest_block_num
    /// The number (height) of the estimated highest block to be synchronized
    pub highest_block_num: BlockNumber,
    // #/components/schemas/SYNC_STATUS/starting_block_hash
    /// The hash of the block from which the sync started
    pub starting_block_hash: BlockHash,
    // #/components/schemas/SYNC_STATUS/starting_block_num
    /// The number (height) of the block from which the sync started
    pub starting_block_num: BlockNumber,
}

// #/components/schemas/TXN
/// The transaction schema, as it appears inside a block
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Txn {
    // #/components/schemas/TXN/variant0
    #[serde(rename = "INVOKE")]
    Invoke(InvokeTxn),
    // #/components/schemas/TXN/variant1
    #[serde(rename = "L1_HANDLER")]
    L1Handler(L1HandlerTxn),
    // #/components/schemas/TXN/variant2
    #[serde(rename = "DECLARE")]
    Declare(DeclareTxn),
    // #/components/schemas/TXN/variant3
    #[serde(rename = "DEPLOY")]
    Deploy(DeployTxn),
    // #/components/schemas/TXN/variant4
    #[serde(rename = "DEPLOY_ACCOUNT")]
    DeployAccount(DeployAccountTxn),
}

// #/components/schemas/TXN_EXECUTION_STATUS
/// The execution status of the transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxnExecutionStatus {
    // #/components/schemas/TXN_EXECUTION_STATUS/REVERTED
    #[serde(rename = "REVERTED")]
    Reverted,
    // #/components/schemas/TXN_EXECUTION_STATUS/SUCCEEDED
    #[serde(rename = "SUCCEEDED")]
    Succeeded,
}

// #/components/schemas/TXN_FINALITY_STATUS
/// The finality status of the transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxnFinalityStatus {
    // #/components/schemas/TXN_FINALITY_STATUS/ACCEPTED_ON_L1
    #[serde(rename = "ACCEPTED_ON_L1")]
    L1,
    // #/components/schemas/TXN_FINALITY_STATUS/ACCEPTED_ON_L2
    #[serde(rename = "ACCEPTED_ON_L2")]
    L2,
}

// #/components/schemas/TXN_HASH
/// The transaction hash, as assigned in StarkNet
#[derive(Debug, Clone, Serialize, Deserialize)]
pub type TxnHash = Felt;

// #/components/schemas/TXN_RECEIPT
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TxnReceipt {
    // #/components/schemas/TXN_RECEIPT/variant0
    #[serde(rename = "INVOKE")]
    Invoke(InvokeTxnReceipt),
    // #/components/schemas/TXN_RECEIPT/variant1
    #[serde(rename = "L1_HANDLER")]
    L1Handler(L1HandlerTxnReceipt),
    // #/components/schemas/TXN_RECEIPT/variant2
    #[serde(rename = "DECLARE")]
    Declare(DeclareTxnReceipt),
    // #/components/schemas/TXN_RECEIPT/variant3
    #[serde(rename = "DEPLOY")]
    Deploy(DeployTxnReceipt),
    // #/components/schemas/TXN_RECEIPT/variant4
    #[serde(rename = "DEPLOY_ACCOUNT")]
    DeployAccount(DeployAccountTxnReceipt),
}

// #/components/schemas/TXN_STATUS
/// The finality status of the transaction, including the case the txn is still in the mempool or failed validation during the block construction phase
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxnStatus {
    // #/components/schemas/TXN_STATUS/ACCEPTED_ON_L1
    #[serde(rename = "ACCEPTED_ON_L1")]
    AcceptedOnL1,
    // #/components/schemas/TXN_STATUS/ACCEPTED_ON_L2
    #[serde(rename = "ACCEPTED_ON_L2")]
    AcceptedOnL2,
    // #/components/schemas/TXN_STATUS/RECEIVED
    #[serde(rename = "RECEIVED")]
    Received,
    // #/components/schemas/TXN_STATUS/REJECTED
    #[serde(rename = "REJECTED")]
    Rejected,
}

// #/components/schemas/TXN_TYPE
/// The type of the transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxnType {
    // #/components/schemas/TXN_TYPE/DECLARE
    #[serde(rename = "DECLARE")]
    Declare,
    // #/components/schemas/TXN_TYPE/DEPLOY
    #[serde(rename = "DEPLOY")]
    Deploy,
    // #/components/schemas/TXN_TYPE/DEPLOY_ACCOUNT
    #[serde(rename = "DEPLOY_ACCOUNT")]
    DeployAccount,
    // #/components/schemas/TXN_TYPE/INVOKE
    #[serde(rename = "INVOKE")]
    Invoke,
    // #/components/schemas/TXN_TYPE/L1_HANDLER
    #[serde(rename = "L1_HANDLER")]
    L1Handler,
}

// #/components/schemas/TYPED_PARAMETER
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypedParameter {
    // #/components/schemas/TYPED_PARAMETER/name
    /// The parameter's name
    pub name: String,
    // #/components/schemas/TYPED_PARAMETER/type
    /// The parameter's type
    #[serde(rename = "type")]
    pub ty: String,
}

// #/methods/starknet_blockHashAndNumber/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockHashAndNumber {
    // #/methods/starknet_blockHashAndNumber/result/_anon/block_hash
    pub block_hash: BlockHash,
    // #/methods/starknet_blockHashAndNumber/result/_anon/block_number
    pub block_number: BlockNumber,
}

// #/methods/starknet_getBlockWithTxHashes/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MaybePendingBlockWithTxHashes {
    // #/methods/starknet_getBlockWithTxHashes/result/_anon/variant0
    Block(BlockWithTxHashes),
    // #/methods/starknet_getBlockWithTxHashes/result/_anon/variant1
    Pending(PendingBlockWithTxHashes),
}

// #/methods/starknet_getBlockWithTxs/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MaybePendingBlockWithTxs {
    // #/methods/starknet_getBlockWithTxs/result/_anon/variant0
    Block(BlockWithTxs),
    // #/methods/starknet_getBlockWithTxs/result/_anon/variant1
    Pending(PendingBlockWithTxs),
}

// #/methods/starknet_getClass/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MaybeDeprecatedContractClass {
    // #/methods/starknet_getClass/result/_anon/variant0
    Deprecated(DeprecatedContractClass),
    // #/methods/starknet_getClass/result/_anon/variant1
    ContractClass(ContractClass),
}

// #/methods/starknet_getEvents/params/filter/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventFilterWithPageRequest {
    // #/components/schemas/EVENT_FILTER/address
    #[serde(default)]
    pub address: Option<Address>,
    // #/components/schemas/EVENT_FILTER/from_block
    #[serde(default)]
    pub from_block: Option<BlockId>,
    // #/components/schemas/EVENT_FILTER/keys
    /// The values used to filter the events
    #[serde(default)]
    pub keys: Option<Vec<Vec<Felt>>>,
    // #/components/schemas/EVENT_FILTER/to_block
    #[serde(default)]
    pub to_block: Option<BlockId>,
    // #/components/schemas/RESULT_PAGE_REQUEST/chunk_size
    pub chunk_size: u64,
    // #/components/schemas/RESULT_PAGE_REQUEST/continuation_token
    /// The token returned from the previous query. If no token is provided the first page is returned.
    #[serde(default)]
    pub continuation_token: Option<String>,
}

// #/methods/starknet_getStateUpdate/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MaybePendingStateUpdate {
    // #/methods/starknet_getStateUpdate/result/_anon/variant0
    Block(StateUpdate),
    // #/methods/starknet_getStateUpdate/result/_anon/variant1
    Pending(PendingStateUpdate),
}

// #/methods/starknet_getTransactionReceipt/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MaybePendingTxnReceipt {
    // #/methods/starknet_getTransactionReceipt/result/_anon/variant0
    Receipt(TxnReceipt),
    // #/methods/starknet_getTransactionReceipt/result/_anon/variant1
    Pending(PendingTxnReceipt),
}

// #/methods/starknet_getTransactionStatus/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TxnStatus {
    // #/methods/starknet_getTransactionStatus/result/_anon/execution_status
    #[serde(default)]
    pub execution_status: Option<TxnExecutionStatus>,
    // #/methods/starknet_getTransactionStatus/result/_anon/finality_status
    pub finality_status: TxnStatus,
}

// #/methods/starknet_syncing/result/_anon
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SyncingStatus {
    // #/methods/starknet_syncing/result/_anon/variant0
    /// only legal value is FALSE here
    False(bool),
    // #/methods/starknet_syncing/result/_anon/variant1
    SyncStatus(SyncStatus),
}
